Send DNS query in one packet when using TCP/TLS
miekg/dns pull request #1219
Opened 2021-02-09 16:02 UTC by ameshkov

Attempt to improve #1200.
This fixes #1199 and this is also crucial for #1218.

This way we'll continue to use `net.Buffers` for TCP connections and only switch to allocating a new buffer for TLS.

2021-02-10 08:37 UTC, tmthrgd requested changes

2021-02-10 08:37 UTC, tmthrgd commented on client.go
> +	copy(msg[2:], p[:])
`s/p[:]/p/`

2021-02-10 08:37 UTC, tmthrgd commented on server.go
> +		copy(msg[2:], m[:])
`s/m[:]/m/`

2021-02-10 08:41 UTC, tmthrgd commented
I think we should back out #934 (the net.Buffers part) and not use net.Buffers at all here. There are far too many conditionals to pass before it batch writes:

```go
// Buffers contains zero or more runs of bytes to write.
//
// On certain machines, for certain types of connections, this is
// optimized into an OS-specific batch write operation (such as
// "writev").
type Buffers [][]byte
```

Currently that happens on darwin dragonfly freebsd illumos linux netbsd openbsd and windows, but not any other Go-supported platforms. It would have been preferable for us if Go had just exposed a writev wrapper directly and allowed us to handle fallbacks as needed.

Ultimately #934 was more about cleaning up the writing code. I switched it to net.Buffers on the assumption it would be faster, but I didn't have any numbers to back that up. I suspect it still probably is, but I don't think it's worth it. It's also clearly much slower for TLS.

2021-02-10 09:10 UTC, ameshkov commented
I am bothered a little by the sheer number of allocations the DNS library makes. If it's possible to avoid extra allocations here at least on Linux, it'd be for the good. Let me please do some tests to check if using `net.Buffers` does any good there.

2021-02-10 10:12 UTC, miekg commented
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Send DNS query in o..." ]
>I think we should back out #934 (the net.Buffers part) and not use net.Buffers
>at all here. There are far too many conditionals to pass before it batch
>writes:

I have no particular attachment to net.Buffers. Only the general sense of that if we can
outsource to the std lib for something non-trivial we should.

This is part of the reason that I'm looking forward to DoH/DoQ, i.e. swap out all the
'let's do networking ourselves, it will be fun' for a vetted, shared, QUIC implemenation.

2021-02-10 10:27 UTC, tmthrgd commented
> I am bothered a little by the sheer number of allocations the DNS library makes. If it's possible to avoid extra allocations here at least on Linux, it'd be for the good. Let me please do some tests to check if using `net.Buffers` does any good there.

By all means benchmark away. It actually shouldn't introduce any new allocations as both buffers escape to the heap as it is. What would change is that instead of a 2-byte and n-byte allocation, you'd get an n-byte and 2+n-byte allocation. The biggest overhead in that case is probably actually the copy, which I don't think would be that significant.

It is unfortunate that allocations are as common as they are, but that's somewhat unavoidable. A dns/v2 could potentially eliminate this in all cases by always packing messages with a length prefix that is sliced off for UDP and kept for TCP. (I feel like I remember one of the proposed x/net/dns packages doing exactly that). That wouldn't be possible with backward compatibility requirements though.

2021-02-10 11:16 UTC, ameshkov commented
Here it is:
https://github.com/ameshkov/dns/blob/bench/issue_test.go#L48

Msg size = 1000

MacOS:
```
BenchmarkNoNetBuffers-16    	    6178	    251207 ns/op	    4453 B/op	      44 allocs/op
BenchmarkNetBuffers-16      	    4820	    259940 ns/op	    3593 B/op	      49 allocs/op
```

Linux:
```
BenchmarkNoNetBuffers-4   	    7790	    161764 ns/op	    4553 B/op	      48 allocs/op
BenchmarkNetBuffers-4     	    8644	    172493 ns/op	    3712 B/op	      53 allocs/op
```

Msg size = 200

MacOS:
```
BenchmarkNoNetBuffers-16    	    6984	    243791 ns/op	    2821 B/op	      44 allocs/op
BenchmarkNetBuffers-16      	    4585	    264033 ns/op	    2780 B/op	      49 allocs/op
```

Linux:
```
BenchmarkNoNetBuffers-4   	    7945	    172557 ns/op	    2964 B/op	      48 allocs/op
BenchmarkNetBuffers-4     	    6979	    185948 ns/op	    2931 B/op	      54 allocs/op
```

2021-02-10 11:22 UTC, rdrozhdzh commented
> A dns/v2 could potentially eliminate this in all cases by always packing messages with a length prefix that is sliced off for UDP and kept for TCP. (I feel like I remember one of the proposed x/net/dns packages doing exactly that). That wouldn't be possible with backward compatibility requirements though.

@tmthrgd , what do you think about my suggestion in https://github.com/miekg/dns/pull/1218#issuecomment-776020259? This is close to what you're saying here, and it looks backward compatible to me, since we'll add another function for providing the data prefixed with length.

2021-02-10 12:13 UTC, tmthrgd commented
> > A dns/v2 could potentially eliminate this in all cases by always packing messages with a length prefix that is sliced off for UDP and kept for TCP. (I feel like I remember one of the proposed x/net/dns packages doing exactly that). That wouldn't be possible with backward compatibility requirements though.
> 
> @tmthrgd , what do you think about my suggestion in [#1218 (comment)](https://github.com/miekg/dns/pull/1218#issuecomment-776020259)? This is close to what you're saying here, and it looks backward compatible to me, since we'll add another function for providing the data prefixed with length.

For some hypothetical dns/v2 I’d say something along those lines would be good. I don’t think it’s really feasible here though, we have exported methods that take the raw message as a []byte (that’s where this change is) and I don’t think duplicating and specialising in higher up methods is ideal, and we have to deal with TSIG (on the server side) that works with []byte. Definitely something to consider though, it might be possible to do as some kind of larger refactoring though.

2021-02-10 13:44 UTC, tmthrgd commented
@ameshkov You might want to try running a benchmark like I did here: https://gist.github.com/tmthrgd/cfcc4b245267cd8d2571eaeeda0f83ad

2021-02-11 14:26 UTC, ameshkov commented
@tmthrgd performance is pretty much the same: https://gist.github.com/ameshkov/66a69888a31328efbf78b45500cda634

2021-02-11 14:50 UTC, ameshkov commented
So far I don't see much difference between using `net.Buffers` and allocating a new array. Updated the PR accordingly.

2021-02-12 01:08 UTC, tmthrgd commented
> @tmthrgd performance is pretty much the same: https://gist.github.com/ameshkov/66a69888a31328efbf78b45500cda634

Thanks for that. It definitely seems like simplicity is the best option here.

2021-02-12 01:08 UTC, tmthrgd approved these changes
LGTM.

2021-02-12 08:28 UTC, miekg commented
this needs a test, unsure how though, but it needs a tests. We keep touching this code and without a test there is no in-tree memory of how things should work/look

2021-02-12 09:06 UTC, ameshkov commented
Well, testing the desired behavior without mocking net.Conn would be rather problematic. Also, it'd require making almost identical tests for both client and server part.

What if I create ioutil.go and move this code there? This way we'd be able to write a simple test checking that a packet is written in one go and avoid duplication.

2021-02-12 09:41 UTC, miekg commented
Would mocking a net.Conn be a lot of code? We would only need to check for the double write, so I'm assuming this could be done in "not a lot of lines of code"?

2021-02-12 10:01 UTC, ameshkov commented
Well, I guess if we just want to check the TLS case, using `tls.Conn` would be enough.

2021-02-12 10:15 UTC, miekg commented
Let's just try and see how it looks? Just detecting the non-double (i.e. single) write should be good enough, so technically this should be doable on the client side only

2021-02-12 10:40 UTC, ameshkov commented
Okay, let's try it. Just added a test for the TLS server, it's rather trivial.

Check it out plz, if this approach works for you, I'll use the same for the dns.Client

2021-02-12 16:49 UTC, tmthrgd commented
If you want a test like that, which is reasonable, it’s very easy to just write a:

```go
type countingConn struct { net.Conn; writes int } 
Func (* countingConn) Write...
```

2021-02-12 16:50 UTC, tmthrgd commented
We definitely don’t want to be half-parsing TLS record headers.

2021-02-12 16:55 UTC, ameshkov commented
This is exactly what I suggested in [the first place](https://github.com/miekg/dns/pull/1219#issuecomment-778071376), but I don't see where to inject this connection into the server, and that's why I suggested moving the code that writes to a separate function and test just it alone.

2021-02-12 16:59 UTC, ameshkov commented
Okay, nvm, I should've read the code more carefully. It's enough to create a `response` instance.

2021-02-12 17:13 UTC, ameshkov commented
Updated the PR, added unit-tests, thanks for the hints!

2021-02-13 02:58 UTC, tmthrgd approved these changes
LGTM.

2021-02-13 18:49 UTC, merged