ReadMsgHeader use bytes pool
miekg/dns pull request #1386
Opened 2022-06-28 02:54 UTC by IIvyPy

I find the  makeslice of ReadMsgHeader will cost much GC time. So I suggest to use bytes pool to avoid the GC cost.

2022-07-07 10:18 UTC, miekg requested changes

2022-07-07 10:18 UTC, miekg commented on client.go
> +func init() {
please, no init functions

2022-07-07 10:18 UTC, miekg commented on client.go
> +// use sync.Pool to avoid gc overhead.
comment doesn't add a lot

2022-07-07 10:18 UTC, miekg commented on client.go
> +	udpPool.New = makeUDPBuffer(DefaultMsgSize)
DefaultMsgSize is 512, a header is max 12 bytes, is this intentional?

2022-07-07 10:19 UTC, miekg commented
your commit message also don't explain anything about this change, it's just a one-liner

So it's on the client you want to use a buffer just like we do on the server side? Any data available (that should be in the ocmmit msg) on why and how this came about??

2023-04-18 03:22 UTC, tmthrgd requested changes

2023-04-18 03:22 UTC, tmthrgd commented on client.go
>  		n, err = io.ReadFull(co.Conn, p)
This is wrong. You're ignoring the length which can be up to 64KiB. This would limit the max message size under TCP to whatever the pool returns.

2023-04-18 03:22 UTC, tmthrgd commented on client.go
> -		}
This code was important. `UDPSize` can be set larger than `MinMsgSize`. You're not handling that at all.

2023-04-18 03:22 UTC, tmthrgd commented on client.go
> -	p = p[:n]
This slice call is important, we only read n-bytes not the full length of p.

2023-04-18 03:25 UTC, tmthrgd commented
I'm sympathetic to the performance concerns here, but this isn't quite the way to go about it. We'd need a pool on the Client struct itself. But considering there's been no movement here in almost a year, I'm going to go ahead and close this PR. Feel free to re-open and address the issues above.

2023-04-18 03:25 UTC, closed without merging