Updates to LOC type RFC1876
miekg/dns pull request #1440
Opened 2023-03-15 22:32 UTC by systemcrash

https://www.rfc-editor.org/rfc/rfc1876

2023-03-16 11:49 UTC, miekg commented on types.go
> +// Various constants used in the LOC RR. See RFC 1876.
fine with this

2023-03-16 23:11 UTC, tmthrgd requested changes
Minor nits.

2023-03-16 23:11 UTC, tmthrgd commented on types_test.go
> +	s := cmToM((0 << 0) + 0)
`<< 4`

2023-03-16 23:11 UTC, tmthrgd commented on types.go
> +	var e = x & 0x0f
`:=` rather than `var ... =`

2023-03-17 01:39 UTC, tmthrgd approved these changes
LGTM.

2023-03-17 01:50 UTC, systemcrash commented on types_test.go
> +	s := cmToM((0 << 0) + 0)
seemed a waste of cpu cycles :)

2023-03-18 11:57 UTC, merged